### ISSUE TITLE
USER STORY #23: Project review 

### ISSUE THREAD

**Issue by JonnyDavison** [JonnyDavison/WildHook#23]
As a **Dev** I can **review the project** so that **I can ensure all the features are satisfactory and the UX/UI is to requirements. Add any new features that may have been added with the Agile approach, plan and implement them.**

**Acceptance Criteria**

- [ ] Features are meeting MVP
- [ ] Additional features are planned, work is scheduled 
- [ ] UX/UI is to requirements
