### ISSUE TITLE
USER STORY #5: Create Template, Static & Media directories

### ISSUE THREAD

**Issue by JonnyDavison** [JonnyDavison/WildHook#5]
As a **Dev** I can **Add directories** so that **My templates, images and styling is accessible and connected to the app**

**Acceptance Criteria**

- [ ] Template, Static & Media directories created 
- [ ] 'Settings.py' Updated to access the directories 
- [ ] Test the files are connected correctly
