### ISSUE TITLE
USER STORY #6: Deployment

### ISSUE THREAD

**Issue by JonnyDavison** [JonnyDavison/WildHook#6]
As a **Dev** I can **Deploy the project** so that **I can view and test the project as a user would throughout the project**

**Acceptance Criteria**

- [ ] Project Visible on Heroku
- [ ] Config Variables are set
- [ ] Templates, Static & Media files are working on the deployed project
